### ISSUE TITLE
Sikkerheds issue muligvis

### ISSUE THREAD

**Issue by liltoto** [Nickhoyer/yousee-musik-til-windows#1]
Hey fedt projekt. Vil jeg ikke kunne være i stand til at publish en ny version("malware") med de her oplysninger?

https://github.com/Nickhoyer/yousee-musik-til-windows/blob/461095e5933b6fdead3120aa3b1e765b601dd9c2/package.json#L25

Plus fandt også en ID der synligt for alle.

https://github.com/Nickhoyer/yousee-musik-til-windows/blob/461095e5933b6fdead3120aa3b1e765b601dd9c2/inject/integrations/discord/discord.js#L5

Jeg vil bare gerne sikre mig at det ikke er noget du har glemt at fjerne 😄

**Comment by Nickhoyer** [comment]
Hej @liltoto mange tak for interessen! 😄 

Som det er lige nu ser jeg ikke nogen sikkerhedsrisiko i det, da alle packaged apps skal undergå en manuel verificering og skal uploades fra mit udvikler account. Jeg tror ikke at de er secrets, men det kunne godt skjules væk - det var bare begrænset hvor meget jeg ville lægge i et weekend projekt

Ang. discord så ser jeg heller ikke clientID som en secret, men det kunne igen sagtens gemmes væk.

Jeg vil holde det i bagtankerne, og er glad for interessen, og så kan det kan være jeg lige føler jeg har tid til at finpudse det hele engang

**Comment by liltoto** [comment]
Okay cool. Jeg har ikke selv leget med de 2 interfaces før, vil bare sikre mig. :) Da jeg selv begår den fejl nogen gange. Endnu engang fedt arbejde og jeg har altid følt jeg har kunne bruge en app i sedet for browser.
