### ISSUE TITLE
Penge.....

### ISSUE THREAD

**Issue by FL0UR1SH** [Nickhoyer/yousee-musik-til-windows#10]
Hej Nickolas
Jeg har brugt de her 12 kroner på din app Yousee musik til windows.
Hvorfor bliver den så ved med at trække 12 kroner pr. dag? Og hvornår stopper det med at trække penge fra mig?

**Comment by Nickhoyer** [comment]
Hej, det er jeg ked af at høre, men min app er tilgængelig frit og gratis i windows store 
https://www.microsoft.com/store/productId/9N7WK34VC3TC
Så det er ikke min app du har købt 😄

**Comment by FL0UR1SH** [comment]
Nå, det var sa mærkeligt, for det nøjagtig de samme ting der står der, logo, deskription, developer. Bortset fra at det link du sendte mig var gratis.....
